### ISSUE TITLE
Modelagem do banco de dados

### ISSUE THREAD

**Issue by cracogabriel** [garager-inc/garager-backend#9]
Eu como desenvolvedor,
desejo modelar o banco de dados em mysql,
para armazenar as informações da aplicação.

as tabelas são:
- Garagem
- Endereço
- Usuário
- Agenda
- Agendamento

**Comment by Chris-cez** [comment]
-- MySQL Workbench Synchronization
-- Generated: 2024-08-12 20:17
-- Version: 1.0
-- Project: Garager-backend
-- Author: CHRISTOPHER EDUARDO ZAI
`
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

CREATE SCHEMA IF NOT EXISTS `workshop` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE IF NOT EXISTS `workshop`.`Workshop` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `Address_id` INT(11) NOT NULL,
  `User_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Workshop_Address_idx` (`Address_id` ASC) VISIBLE,
  INDEX `fk_Workshop_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Workshop_Address`
    FOREIGN KEY (`Address_id`)
    REFERENCES `workshop`.`Address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Workshop_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `workshop`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `workshop`.`Address` (
  `id` INT(11) NOT NULL,
  `street` VARCHAR(255) NOT NULL,
  `number` VARCHAR(255) NOT NULL,
  `city` VARCHAR(255) NOT NULL,
  `zip_code` VARCHAR(255) NOT NULL,
  `state` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `workshop`.`User` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(255) NOT NULL,
  `cpf` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `workshop`.`Available_slots` (
  `id` INT(11) NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  `Workshop_id` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Available_slots_Workshop1_idx` (`Workshop_id` ASC) VISIBLE,
  CONSTRAINT `fk_Available_slots_Workshop1`
    FOREIGN KEY (`Workshop_id`)
    REFERENCES `workshop`.`Workshop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE TABLE IF NOT EXISTS `workshop`.`appointment` (
  `id` INT(11) NOT NULL,
  `User_id` INT(11) NOT NULL,
  `Workshop_id` INT(11) NOT NULL,
  `start_time` DATETIME NOT NULL,
  `end_time` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_appointment_User1_idx` (`User_id` ASC) VISIBLE,
  INDEX `fk_appointment_Workshop1_idx` (`Workshop_id` ASC) VISIBLE,
  CONSTRAINT `fk_appointment_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `workshop`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_appointment_Workshop1`
    FOREIGN KEY (`Workshop_id`)
    REFERENCES `workshop`.`Workshop` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
`
